# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Deep Rob
tagline: CSCI5980 - Deep Learning for Robot Perception and Manipulation
description: This course covers the necessary background of neural-network-based deep learning for robot perception – building on advancements in computer vision that enable robots to physically manipulate objects
author: Anthony Opipari, Karthik Desingh
baseurl: '/CSCI5980-Spr23-DeepRob' # the subpath of your site, e.g. /blog
url: 'https://rpm-lab.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
logo: "/assets/logos/favicons/UMinn_favicon_dark.png"

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2
color_scheme: minny
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links_new_tab: true
aux_links:
  Forum:
    - 'https://edstem.org/us/courses/31008/discussion/'
  Autograder:
    - 'https://cse-ag-csci5980.cs.umn.edu/web/course/2'   
  Gradescope:
    - 'https://www.gradescope.com/courses/481744'  
  RPM Lab:
    - 'https://rpm-lab.github.io/'   
  '<img src="/CSCI5980-Spr23-DeepRob//assets/logos/MnRI_logo.png" class="nav-img">':
    - 'https://cse.umn.edu/mnri'

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
